-- MySQL Script generated by MySQL Workbench
-- Sun Apr 17 17:10:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BlaBlaCar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BlaBlaCar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BlaBlaCar` DEFAULT CHARACTER SET utf8 ;
USE `BlaBlaCar` ;

-- -----------------------------------------------------
-- Table `BlaBlaCar`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BlaBlaCar`.`Users` (
  `Login` VARCHAR(30) GENERATED ALWAYS AS () VIRTUAL,
  `Password` VARCHAR(8) GENERATED ALWAYS AS () VIRTUAL,
  `Name` VARCHAR(20) GENERATED ALWAYS AS (),
  `Family` VARCHAR(30) GENERATED ALWAYS AS (),
  `Age` INT GENERATED ALWAYS AS () VIRTUAL,
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC) VISIBLE,
  PRIMARY KEY (`Login`),
  UNIQUE INDEX `Password_UNIQUE` (`Password` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BlaBlaCar`.`Ferrymans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BlaBlaCar`.`Ferrymans` (
  `Login` VARCHAR(30) GENERATED ALWAYS AS () VIRTUAL,
  `Password` VARCHAR(8) GENERATED ALWAYS AS () VIRTUAL,
  `Name` VARCHAR(20) GENERATED ALWAYS AS (),
  `Family` VARCHAR(30) GENERATED ALWAYS AS () STORED,
  `Age` INT GENERATED ALWAYS AS () VIRTUAL,
  `Еxperience` INT GENERATED ALWAYS AS () VIRTUAL,
  `Birthday` DATETIME GENERATED ALWAYS AS () VIRTUAL,
  `PassportSeries` INT GENERATED ALWAYS AS () VIRTUAL,
  `PassportNomer` INT GENERATED ALWAYS AS () VIRTUAL,
  PRIMARY KEY (`Login`),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC) VISIBLE,
  UNIQUE INDEX `Password_UNIQUE` (`Password` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BlaBlaCar`.`ChekPointsList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BlaBlaCar`.`ChekPointsList` (
  `CheckPointName` VARCHAR(50) GENERATED ALWAYS AS () VIRTUAL,
  `LatitudePoint` INT GENERATED ALWAYS AS () VIRTUAL,
  `LongitudePoint` INT GENERATED ALWAYS AS (),
  `Rides_idRides` INT NOT NULL,
  `Rides_Users_Login` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`CheckPointName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BlaBlaCar`.`Rides`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BlaBlaCar`.`Rides` (
  `idRides` INT NOT NULL AUTO_INCREMENT,
  `Transport` VARCHAR(45) GENERATED ALWAYS AS () VIRTUAL,
  `Free places` INT GENERATED ALWAYS AS () VIRTUAL,
  `Ferrymans_Login` VARCHAR(30) NOT NULL,
  `Users_Login` VARCHAR(30) NOT NULL,
  `CheckPointNameDeparture` VARCHAR(50) GENERATED ALWAYS AS () VIRTUAL,
  `ChekPointsNameArrival` VARCHAR(50) GENERATED ALWAYS AS (),
  `Date` DATE GENERATED ALWAYS AS () VIRTUAL,
  `WayTime` INT GENERATED ALWAYS AS (),
  `Price` INT GENERATED ALWAYS AS () VIRTUAL,
  PRIMARY KEY (`idRides`, `Users_Login`),
  UNIQUE INDEX `idRides_UNIQUE` (`idRides` ASC) VISIBLE,
  INDEX `fk_Rides_Ferrymans_idx` (`Ferrymans_Login` ASC) VISIBLE,
  INDEX `fk_Rides_Users1_idx` (`Users_Login` ASC) VISIBLE,
  INDEX `fk_Rides_ChekPointsList1_idx` (`CheckPointNameDeparture` ASC) VISIBLE,
  INDEX `fk_Rides_ChekPointsList2_idx` (`ChekPointsNameArrival` ASC) VISIBLE,
  CONSTRAINT `fk_Rides_Ferrymans`
    FOREIGN KEY (`Ferrymans_Login`)
    REFERENCES `BlaBlaCar`.`Ferrymans` (`Login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rides_Users1`
    FOREIGN KEY (`Users_Login`)
    REFERENCES `BlaBlaCar`.`Users` (`Login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rides_ChekPointsList1`
    FOREIGN KEY (`CheckPointNameDeparture`)
    REFERENCES `BlaBlaCar`.`ChekPointsList` (`CheckPointName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rides_ChekPointsList2`
    FOREIGN KEY (`ChekPointsNameArrival`)
    REFERENCES `BlaBlaCar`.`ChekPointsList` (`CheckPointName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
